
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Basalt gen
		block_list_basalt = ["minecraft:basalt|100"]
		#Cobble gen
		block_list_cobble = ["minecraft:cobblestone|100"]
		#Stone gen
		block_list_stone = ["minecraft:stone|100"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [["cobblestone", "minecraft:bedrock", ["create:andesite_cobblestone|25", "create:granite_cobblestone|25", "create:diorite_cobblestone|25", "create:gabbro_cobblestone|25"]], ["stone", "minecraft:bedrock", ["minecraft:andesite|25", "minecraft:granite|25", "minecraft:diorite|25", "create:gabbro|25"]]]

