
#Exchangers Config
[modules]
	#If true, enables Immersive Engineering-based exchangers (Requires Immersive Engineering to be installed).
	immersiveEngineeringModule = true
	#If true, enables Vanilla-based exchangers.
	vanillaModule = true
	#If true, enables Ender IO-based exchangers (Requires Ender IO to be installed).
	enderIOModule = true
	#If true, enables Mekanism-based exchangers (Requires Mekanism to be installed).
	mekanismModule = true
	#If true, enables Ender IO Endergy-based exchangers (Requires Ender IO Endergy to be installed).
	enderIOEndergyModule = true
	#If true, enables Thermal Series-based exchangers (Requires Thermal Foundation and Thermal Innovation to be installed).
	thermalModule = true
	#If true, enables special exchangers (e.g. Tuberous Exchanger).
	specialModule = true

[vanilla_tweaks]
	#Set the max range for Emerald Exchanger
	#Range: 0 ~ 12
	emeraldExchangerMaxRange = 5
	#Set the max harvest level for Stone Exchanger
	#Range: > 0
	stoneExchangerMaxHarvestLevel = 1
	#Set the max range for End Exchanger
	#Range: 0 ~ 12
	endExchangerMaxRange = 7
	#Set the max harvest level for Iron Exchanger
	#Range: > 0
	ironExchangerMaxHarvestLevel = 2
	#Set the max range for Wooden Exchanger
	#Range: 0 ~ 12
	woodenExchangerMaxRange = 0
	#Set the durability for Emerald Exchanger
	#Range: > 1
	emeraldExchangerMaxDamage = 8192
	#Set the max range for Obsidian Exchanger
	#Range: 0 ~ 12
	obsidianExchangerMaxRange = 6
	#Set the durability for End Exchanger
	#Range: > 1
	endExchangerMaxDamage = 32768
	#Set the max range for Golden Exchanger
	#Range: 0 ~ 12
	goldenExchangerMaxRange = 2
	#Set the max range for Stone Exchanger
	#Range: 0 ~ 12
	stoneExchangerMaxRange = 1
	#Set the max harvest level for Golden Exchanger
	#Range: > 0
	goldenExchangerMaxHarvestLevel = 1
	#Set the max range for Diamond Exchanger
	#Range: 0 ~ 12
	diamondExchangerMaxRange = 4
	#Set the max harvest level for Emerald Exchanger
	#Range: > 0
	emeraldExchangerMaxHarvestLevel = 4
	#Set the max harvest level for Diamond Exchanger
	#Range: > 0
	diamondExchangerMaxHarvestLevel = 3
	#Set the durability for Iron Exchanger
	#Range: > 1
	ironExchangerMaxDamage = 1024
	#Set the durability for Stone Exchanger
	#Range: > 1
	stoneExchangerMaxDamage = 384
	#Set the max harvest level for End Exchanger
	#Range: > 0
	endExchangerMaxHarvestLevel = 5
	#Set the durability for Golden Exchanger
	#Range: > 1
	goldenExchangerMaxDamage = 512
	#Set the durability for Wooden Exchanger
	#Range: > 1
	woodenExchangerMaxDamage = 256
	#Set the durability for Diamond Exchanger
	#Range: > 1
	diamondExchangerMaxDamage = 4096
	#Set the max harvest level for Wooden Exchanger
	#Range: > 0
	woodenExchangerMaxHarvestLevel = 0
	#Set the max harvest level for Obsidian Exchanger
	#Range: > 0
	obsidianExchangerMaxHarvestLevel = 4
	#Set the durability for Obsidian Exchanger
	#Range: > 1
	obsidianExchangerMaxDamage = 16384
	#Set the max range for Iron Exchanger
	#Range: 0 ~ 12
	ironExchangerMaxRange = 3

[ender_io_tweaks]
	#Set the energy capacity for Pulsating Iron Exchanger
	#Range: > 1000
	pulsatingIronExchangerMaxEnergy = 250000
	#Set the energy consumption per block for Energetic Exchanger
	#Range: > 1
	energeticExchangerPerBlockUse = 1000
	#Set the energy consumption per block for Vibrant Exchanger
	#Range: > 1
	vibrantExchangerPerBlockUse = 2500
	#Set the energy consumption per block for Conductive Iron Exchanger
	#Range: > 1
	conductiveIronExchangerPerBlockUse = 50
	#Set the max range for Electrical Steel Exchanger
	#Range: 0 ~ 12
	electricalSteelExchangerMaxRange = 4
	#Set the energy capacity for Dark Steel Exchanger
	#Range: > 1000
	darkSteelExchangerMaxEnergy = 10000000
	#Set the energy capacity for End Steel Exchanger
	#Range: > 1000
	endSteelExchangerMaxEnergy = 50000000
	#Set the energy consumption per block for End Steel Exchanger
	#Range: > 1
	endSteelExchangerPerBlockUse = 5000
	#Set the energy capacity for Electrical Steel Exchanger
	#Range: > 1000
	electricalSteelExchangerMaxEnergy = 1000000
	#Set the max harvest level for Conductive Iron Exchanger
	#Range: > 0
	conductiveIronExchangerMaxHarvestLevel = 1
	#Set the energy capacity for Conductive Iron Exchanger
	#Range: > 1000
	conductiveIronExchangerMaxEnergy = 50000
	#Set the max range for Vibrant Exchanger
	#Range: 0 ~ 12
	vibrantExchangerMaxRange = 7
	#Set the max harvest level for End Steel Exchanger
	#Range: > 0
	endSteelExchangerMaxHarvestLevel = 5
	#Set the energy capacity for Energetic Exchanger
	#Range: > 1000
	energeticExchangerMaxEnergy = 5000000
	#Set the energy consumption per block for Dark Steel Exchanger
	#Range: > 1
	darkSteelExchangerPerBlockUse = 1500
	#Set the max range for End Steel Exchanger
	#Range: 0 ~ 12
	endSteelExchangerMaxRange = 7
	#Set the max harvest level for Vibrant Exchanger
	#Range: > 0
	vibrantExchangerMaxHarvestLevel = 4
	#Set the max range for Dark Steel Exchanger
	#Range: 0 ~ 12
	darkSteelExchangerMaxRange = 6
	#Set the energy capacity for Vibrant Exchanger
	#Range: > 1000
	vibrantExchangerMaxEnergy = 25000000
	#Set the energy consumption per block for Pulsating Iron Exchanger
	#Range: > 1
	pulsatingIronExchangerPerBlockUse = 100
	#Set the max harvest level for Energetic Exchanger
	#Range: > 0
	energeticExchangerMaxHarvestLevel = 3
	#Set the max harvest level for Pulsating Iron Exchanger
	#Range: > 0
	pulsatingIronExchangerMaxHarvestLevel = 2
	#Set the max range for Energetic Exchanger
	#Range: 0 ~ 12
	energeticExchangerMaxRange = 5
	#Set the energy consumption per block for Electrical Steel Exchanger
	#Range: > 1
	electricalSteelExchangerPerBlockUse = 500
	#Set the max harvest level for Electrical Steel Exchanger
	#Range: > 0
	electricalSteelExchangerMaxHarvestLevel = 3
	#Set the max range for Conductive Iron Exchanger
	#Range: 0 ~ 12
	conductiveIronExchangerMaxRange = 1
	#Set the max range for Pulsating Iron Exchanger
	#Range: 0 ~ 12
	pulsatingIronExchangerMaxRange = 2
	#Set the max harvest level for Dark Steel Exchanger
	#Range: > 0
	darkSteelExchangerMaxHarvestLevel = 4

[ender_io_endergy_tweaks]
	#Set the max range for Crude Steel Exchanger
	#Range: 0 ~ 12
	crudeSteelExchangerMaxRange = 1
	#Set the energy consumption per block for Vivid Exchanger
	#Range: > 1
	vividExchangerPerBlockUse = 500
	#Set the energy capacity for Energetic Silver Exchanger
	#Range: > 1000
	energeticSilverExchangerMaxEnergy = 250000
	#Set the max harvest level for Vivid Exchanger
	#Range: > 0
	vividExchangerMaxHarvestLevel = 3
	#Set the energy consumption per block for Stellar Exchanger
	#Range: > 1
	stellarExchangerPerBlockUse = 5000
	#Set the energy consumption per block for Crude Steel Exchanger
	#Range: > 1
	crudeSteelExchangerPerBlockUse = 50
	#Set the energy capacity for Melodic Exchanger
	#Range: > 1000
	melodicExchangerMaxEnergy = 50000000
	#Set the energy consumption per block for Energetic Silver Exchanger
	#Range: > 1
	energeticSilverExchangerPerBlockUse = 100
	#Set the energy capacity for Vivid Exchanger
	#Range: > 1000
	vividExchangerMaxEnergy = 1000000
	#Set the energy capacity for Crude Steel Exchanger
	#Range: > 1000
	crudeSteelExchangerMaxEnergy = 50000
	#Set the energy consumption per block for Crystalline Exchanger
	#Range: > 1
	crystallineExchangerPerBlockUse = 1500
	#Set the max harvest level for Crystalline Exchanger
	#Range: > 0
	crystallineExchangerMaxHarvestLevel = 3
	#Set the max range for Stellar Exchanger
	#Range: 0 ~ 12
	stellarExchangerMaxRange = 9
	#Set the max harvest level for Energetic Silver Exchanger
	#Range: > 0
	energeticSilverExchangerMaxHarvestLevel = 2
	#Set the energy capacity for Crystalline Exchanger
	#Range: > 1000
	crystallineExchangerMaxEnergy = 10000000
	#Set the max range for Crystalline Exchanger
	#Range: 0 ~ 12
	crystallineExchangerMaxRange = 5
	#Set the max range for Energetic Silver Exchanger
	#Range: 0 ~ 12
	energeticSilverExchangerMaxRange = 2
	#Set the max harvest level for Stellar Exchanger
	#Range: > 0
	stellarExchangerMaxHarvestLevel = 5
	#Set the max harvest level for Crude Steel Exchanger
	#Range: > 0
	crudeSteelExchangerMaxHarvestLevel = 1
	#Set the energy capacity for Stellar Exchanger
	#Range: > 1000
	stellarExchangerMaxEnergy = 100000000
	#Set the energy consumption per block for Melodic Exchanger
	#Range: > 1
	melodicExchangerPerBlockUse = 2500
	#Set the max harvest level for Melodic Exchanger
	#Range: > 0
	melodicExchangerMaxHarvestLevel = 4
	#Set the max range for Melodic Exchanger
	#Range: 0 ~ 12
	melodicExchangerMaxRange = 7
	#Set the max range for Vivid Exchanger
	#Range: 0 ~ 12
	vividExchangerMaxRange = 4

[thermal_tweaks]
	#Set the max range for Reinforced Exchanger
	#Range: 0 ~ 12
	reinforcedExchangerMaxRange = 5
	#Set the energy consumption per block for Hardened Exchanger
	#Range: > 1
	hardenedExchangerPerBlockUse = 150
	#Set the energy capacity for Hardened Exchanger
	#Range: > 1000
	hardenedExchangerMaxEnergy = 500000
	#Set the max range for Hardened Exchanger
	#Range: 0 ~ 12
	hardenedExchangerMaxRange = 3
	#Set the energy consumption per block for Signalum Exchanger
	#Range: > 1
	signalumExchangerPerBlockUse = 500
	#Set the max harvest level for Hardened Exchanger
	#Range: > 0
	hardenedExchangerMaxHarvestLevel = 2
	#Set the max harvest level for Reinforced Exchanger
	#Range: > 0
	reinforcedExchangerMaxHarvestLevel = 3
	#Set the max harvest level for Resonant Exchanger
	#Range: > 0
	resonantExchangerMaxHarvestLevel = 4
	#Set the max harvest level for Signalum Exchanger
	#Range: > 0
	signalumExchangerMaxHarvestLevel = 4
	#Set the energy capacity for Reinforced Exchanger
	#Range: > 1000
	reinforcedExchangerMaxEnergy = 1000000
	#Set the energy consumption per block for Reinforced Exchanger
	#Range: > 1
	reinforcedExchangerPerBlockUse = 250
	#Set the energy consumption per block for Leadstone Exchanger
	#Range: > 1
	leadstoneExchangerPerBlockUse = 50
	#Set the energy consumption per block for Resonant Exchanger
	#Range: > 1
	resonantExchangerPerBlockUse = 1500
	#Set the max harvest level for Leadstone Exchanger
	#Range: > 0
	leadstoneExchangerMaxHarvestLevel = 1
	#Set the energy capacity for Resonant Exchanger
	#Range: > 1000
	resonantExchangerMaxEnergy = 25000000
	#Set the max range for Resonant Exchanger
	#Range: 0 ~ 12
	resonantExchangerMaxRange = 7
	#Set the max range for Signalum Exchanger
	#Range: 0 ~ 12
	signalumExchangerMaxRange = 6
	#Set the energy capacity for Leadstone Exchanger
	#Range: > 1000
	leadstoneExchangerMaxEnergy = 100000
	#Set the max range for Leadstone Exchanger
	#Range: 0 ~ 12
	leadstoneExchangerMaxRange = 1
	#Set the energy capacity for Signalum Exchanger
	#Range: > 1000
	signalumExchangerMaxEnergy = 10000000

[mekanism_tweaks]
	#Set the energy capacity for Elite Exchanger
	#Range: > 1000
	eliteExchangerMaxEnergy = 5000000
	#Set the max harvest level for Ultimate Exchanger
	#Range: > 0
	ultimateExchangerMaxHarvestLevel = 4
	#Set the energy capacity for Basic Exchanger
	#Range: > 1000
	basicExchangerMaxEnergy = 250000
	#Set the max range for Ultimate Exchanger
	#Range: 0 ~ 12
	ultimateExchangerMaxRange = 7
	#Set the max harvest level for Advanced Exchanger
	#Range: > 0
	advancedExchangerMaxHarvestLevel = 2
	#Set the energy consumption per block for Ultimate Exchanger
	#Range: > 1
	ultimateExchangerPerBlockUse = 1000
	#Set the energy consumption per block for Advanced Exchanger
	#Range: > 1
	advancedExchangerPerBlockUse = 150
	#Set the energy capacity for Ultimate Exchanger
	#Range: > 1000
	ultimateExchangerMaxEnergy = 10000000
	#Set the energy consumption per block for Basic Exchanger
	#Range: > 1
	basicExchangerPerBlockUse = 50
	#Set the energy capacity for Advanced Exchanger
	#Range: > 1000
	advancedExchangerMaxEnergy = 1000000
	#Set the max range for Advanced Exchanger
	#Range: 0 ~ 12
	advancedExchangerMaxRange = 5
	#Set the max range for Basic Exchanger
	#Range: 0 ~ 12
	basicExchangerMaxRange = 3
	#Set the max harvest level for Elite Exchanger
	#Range: > 0
	eliteExchangerMaxHarvestLevel = 3
	#Set the energy consumption per block for Elite Exchanger
	#Range: > 1
	eliteExchangerPerBlockUse = 500
	#Set the max range for Elite Exchanger
	#Range: 0 ~ 12
	eliteExchangerMaxRange = 6
	#Set the max harvest level for Basic Exchanger
	#Range: > 0
	basicExchangerMaxHarvestLevel = 1

[immersive_engineering_tweaks]
	#Set the energy consumption per block for LV Exchanger
	#Range: > 1
	lvExchangerPerBlockUse = 50
	#Set the max harvest level for MV Exchanger
	#Range: > 0
	mvExchangerMaxHarvestLevel = 3
	#Set the max harvest level for HV Exchanger
	#Range: > 0
	hvExchangerMaxHarvestLevel = 4
	#Set the max range for LV Exchanger
	#Range: 0 ~ 12
	lvExchangerMaxRange = 3
	#Set the energy consumption per block for MV Exchanger
	#Range: > 1
	mvExchangerPerBlockUse = 250
	#Set the max range for HV Exchanger
	#Range: 0 ~ 12
	hvExchangerMaxRange = 7
	#Set the max range for MV Exchanger
	#Range: 0 ~ 12
	mvExchangerMaxRange = 5
	#Set the energy consumption per block for HV Exchanger
	#Range: > 1
	hvExchangerPerBlockUse = 500
	#Set the max harvest level for LV Exchanger
	#Range: > 0
	lvExchangerMaxHarvestLevel = 2
	#Set the energy capacity for MV Exchanger
	#Range: > 1000
	mvExchangerMaxEnergy = 500000
	#Set the energy capacity for LV Exchanger
	#Range: > 1000
	lvExchangerMaxEnergy = 100000
	#Set the energy capacity for HV Exchanger
	#Range: > 1000
	hvExchangerMaxEnergy = 2500000

[recipe_tweaks]
	#Set the recipes type for Immersive Engineering-based exchangers:
	#'easy'     Easy recipes, non-progressive, lowest recipe costs.
	#'normal'   Normal recipes, progressive, moderate recipe costs.
	#'hard'     Hard recipes, progressive, expensive recipe costs.
	immersiveEngineeringRecipesType = "normal"
	#Set the recipes type for Ender IO-based exchangers:
	#'easy'     Easy recipes, non-progressive, lowest recipe costs.
	#'normal'   Normal recipes, progressive, moderate recipe costs.
	#'hard'     Hard recipes, progressive, expensive recipe costs.
	enderIORecipesType = "normal"
	#Set the recipes type for Mekanism-based exchangers:
	#'easy'     Easy recipes, non-progressive, lowest recipe costs.
	#'normal'   Normal recipes, progressive, moderate recipe costs.
	#'hard'     Hard recipes, progressive, expensive recipe costs.
	mekanismRecipesType = "normal"
	#Set the recipes type for Thermal Series-based exchangers:
	#'easy'     Easy recipes, non-progressive, lowest recipe costs.
	#'normal'   Normal recipes, progressive, moderate recipe costs.
	#'hard'     Hard recipes, progressive, expensive recipe costs.
	thermalRecipesType = "normal"
	#Set the recipes type for Ender IO Endergy-based exchangers:
	#'easy'     Easy recipes, non-progressive, lowest recipe costs.
	#'normal'   Normal recipes, progressive, moderate recipe costs.
	#'hard'     Hard recipes, progressive, expensive recipe costs.
	enderIOEndergyRecipesType = "normal"
	#Set the recipes type for Vanilla-based exchangers:
	#'easy'     Easy recipes, non-progressive, lowest recipe costs.
	#'normal'   Normal recipes, progressive, moderate recipe costs.
	#'hard'     Hard recipes, progressive, expensive recipe costs.
	vanillaRecipesType = "normal"

[misc]
	#Certain blocks might be blacklisted by Exchangers if they're Tile Entities.
	#Put a list of block registry names that you wish to be whitelisted from Exchangers.
	#Separate each entry with semicolon.
	#(e.g. "tconstruct:seared;thermal:energy_cell;minecraft:conduit")
	blocksWhitelist = "tconstruct:seared"
	#If true, allows the Holding Enchantment from CoFH Core to be used on Powered Exchangers
	#Calculation formula: Base Energy + (Base Energy * Enchantment Level / 2)
	holdingEnchantment = true
	#If true, allows Unbreaking Enchantment to affect Powered Exchangers
	unbreakingPoweredExchangers = true
	#Put a list of block registry names that you wish to be blacklisted from Exchangers.
	#Note: Blacklisting a block will prevent it from being selected or being exchanged.
	#Separate each entry with semicolon.
	#(e.g. "minecraft:grass;minecraft:cake;minecraft:dragon_egg")
	blocksBlacklist = ""
	#If true, enables Silk Touch (gets the blocks itself rather than drops) on all Exchangers
	doExchangersSilkTouch = true
	#Set the energy unit shown on Powered Exchangers:
	#'FE'     Forge Energy
	#'RF'     Redstone Flux
	energyUnit = "FE"

