
[Patches_Sizes]
	#
	#Dirt Stone Patches Size (default=60)
	#Range: 1 ~ 100
	patch_size_dirtstone = 1
	#
	#Lavastone Patches Size (default=40)
	#Range: 1 ~ 100
	patch_size_lavastone = 40
	#
	#Dirt Patches Size (default=40)
	#Range: 1 ~ 100
	patch_size_dirt = 40
	#
	#Broken Stone Patches Size (default=24)
	#Range: 1 ~ 100
	patch_size_brokenstone = 24
	#
	#Sediment Stone Patches Size (default=40)
	#Range: 1 ~ 100
	patch_size_sedimentstone = 70
	#
	#Marlstone Patches Size (default=40)
	#Range: 1 ~ 100
	patch_size_marlstone = 60
	#
	#Old Stone Patches Size (default=40)
	#Range: 1 ~ 100
	patch_size_oldstone = 40
	#
	#Packed Ice Patches Size (default=60)
	#Range: 1 ~ 100
	patch_size_packed_ice = 60

[Spawn_Rates]

	[Spawn_Rates.Blocks]
		#
		#Packed Ice Spawn Rate (default=5)
		#Range: 1 ~ 50
		spawnrate_block_packed_ice = 5
		#
		#Lavastone Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_block_lavastone = 8
		#
		#Old Stone Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_block_oldstone = 10
		#
		#Broken Stone Spawn Rate (default=12)
		#Range: 1 ~ 50
		spawnrate_block_brokenstone = 6
		#
		#Dirt Stone Spawn Rate (default=5)
		#Range: 1 ~ 50
		spawnrate_block_dirtstone = 1
		#
		#Marlstone Spawn Rate (default=5)
		#Range: 1 ~ 50
		spawnrate_block_marlstone = 5
		#
		#Sediment Stone Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_block_sedimentstone = 3
		#
		#Dirt Spawn Rate (default=5)
		#Range: 1 ~ 50
		spawnrate_block_dirt = 5

	[Spawn_Rates.Vines]
		#
		#Cave Vine Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_cave_vine = 10

	[Spawn_Rates.Mushrooms]
		#
		#Lumishroom Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_mushroom_lumishroom = 1
		#
		#Goldishroom Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_mushroom_goldishroom = 10
		#
		#Shinyshroom Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_mushroom_shinyshroom = 1
		#
		#Fluoshroom Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_mushroom_fluoshroom = 5
		#
		#Sweetshroom Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_mushroom_sweetshroom = 5
		#
		#Rockshroom Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_mushroom_rockshroom = 10

	[Spawn_Rates.Mosses]
		#
		#Fire Moss Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_moss_fire = 10
		#
		#Hanging Roots Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_moss_hanging_roots = 10
		#
		#Frozen Moss Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_moss_frozen = 10
		#
		#Dry Moss Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_moss_dry = 10
		#
		#Humid Moss Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_moss_humid = 10

	[Spawn_Rates.Rocks]
		#
		#Rock Piles Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_rock_rockpiles = 10
		#
		#Stalagmite Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_rock_stalagmites = 10
		#
		#Pebble Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_rock_pebbles = 10
		#
		#Flint Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_rock_flints = 10
		#
		#Stalactite Spawn Rate (default=10)
		#Range: 1 ~ 50
		spawnrate_rock_stalactites = 10

	[Spawn_Rates.Structures]
		#
		#Spruce Cabins Spawn Rate (default=7)
		#Range: 1 ~ 10
		spawnrate_structure_cabins_spruce = 3
		#
		#Ice Dungeons Spawn Rate (default=5)
		#Range: 1 ~ 10
		spawnrate_structure_dungeons_ice = 1
		#
		#Cobblestone Dungeons Spawn Rate (default=5)
		#Range: 1 ~ 10
		spawnrate_structure_dungeons_cobblestone = 1
		#
		#Lavastone Dungeons Spawn Rate (default=5)
		#Range: 1 ~ 10
		spawnrate_structure_dungeons_lavastone = 1
		#
		#Oak Cabins Spawn Rate (default=7)
		#Range: 1 ~ 10
		spawnrate_structure_cabins_oak = 4
		#
		#Tall Cobblestone Dungeons Spawn Rate (default=5)
		#Range: 1 ~ 10
		spawnrate_structure_dungeons_tall_cobblestone = 2
		#
		#Bricks Cabins Spawn Rate (default=7)
		#Range: 1 ~ 10
		spawnrate_structure_cabins_bricks = 4
		#
		#Jungle Cabins Spawn Rate (default=7)
		#Range: 1 ~ 10
		spawnrate_structure_cabins_jungle = 3
		#
		#Tall Lavastone Dungeons Spawn Rate (default=5)
		#Range: 1 ~ 10
		spawnrate_structure_dungeons_tall_lavastone = 1
		#
		#Acacia Cabins Spawn Rate (default=7)
		#Range: 1 ~ 10
		spawnrate_structure_cabins_acacia = 4
		#
		#Cobblestone Cabins Spawn Rate (default=7)
		#Range: 1 ~ 10
		spawnrate_structure_cabins_cobblestone = 4

[Spawn_Conditions]

	[Spawn_Conditions.Blocks]
		#
		#Generate Dirt
		gen_block_dirt = false
		#
		#Generate Marlstone
		gen_block_marlstone = false
		#
		#Generate Lavastone
		gen_block_lavastone = false
		#
		#Generate Dirt Stone
		gen_block_dirtstone = false
		#
		#Generate Packed Ice
		gen_block_packed_ice = false
		#
		#Generate Broken Stone
		gen_block_brokenstone = true
		#
		#Generate Sediment Stone
		gen_block_sedimentstone = false
		#
		#Generate Old Stone
		gen_block_oldstone = false

	[Spawn_Conditions.Vines]
		#
		#Generate Vines
		gen_vines = false

	[Spawn_Conditions.Mushrooms]
		#
		#Generate Mushrooms
		gen_mushrooms = false

	[Spawn_Conditions.Mosses]
		#
		#Generate Mosses
		gen_mosses = false

	[Spawn_Conditions.Rocks]
		#
		#Generate Flints
		gen_rock_flints = false
		#
		#Generate Pebbles
		gen_rock_pebbles = true
		#
		#Generate Rock Piles
		gen_rock_rockpiles = true
		#
		#Generate Stalagmites
		gen_rock_stalagmites = true
		#
		#Generate Stalactites
		gen_rock_stalactites = true

	[Spawn_Conditions.Structures]
		#
		#Generate Cabins
		gen_structure_cabins = true
		#
		#Generate Dungeons
		gen_structure_dungeons = true

[Items]
	#
	#Health amount given by the bandage (1 = half heart) (default=4)
	#Range: 1 ~ 40
	item_bandage_health = 4
	#
	#Healing items cooldown in seconds (default=5)
	#Range: 1 ~ 30
	item_medecine_cooldown = 5

