
#Visual Settings
[visual]
	#Disables holiday themed visual content such as familiar skins.
	disableHolidayTheming = false
	#Disables the headache- and possibly seizure-inducing visual effects of Demon's Dream.
	disableDemonsDreamShaders = false

#Misc Settings
[misc]
	#Sync JEI search in storage actuator.
	syncJeiSearch = false

