#Write here a list of custom overrides when right clicking a block. It must be blockRightClicked,blockToTransformTo. Blocks must have the format modid:blockid. E.g. minecraft:coarse_dirt,minecraft:grass_path will make coarse dirt transform to path when right-clicked with a shovel. You can even use tags.
Overrides = ["minecraft:dirt,minecraft:grass_path", "minecraft:podzol,minecraft:grass_path", "minecraft:grass_path,minecraft:dirt", "minecraft:farmland,minecraft:dirt"]
#Write here a list of items that shouldn't execute mod's path to dirt code. Items must have the format modid:itemid. Item Tags can be used.
"Item Blacklist" = ["quark:pickarang", "quark:flamerang"]
#If true the player must be sneaking to make the mod work.
"Require Sneaking" = false

