
[general]
	#Defines if the SyncChunkWrite config should be not forcefully set to false. Note: SyncChunkWrite "May" Prevent data corruption. Though this was only enabled since 1.16 before it was always disabled. Downside of this is that HDDs/SSDs during pregen are at 100% usage ALL the time instead of less then 5%. This can lead to hardware failure much much much much more quickly. This is why the override is enabled by default
	"Disable ChunkSyncOverride" = false
	#Defines if the Profiler should run in the background or not
	enable-profiler = false
	#Defines how many milliseconds the Chunk Deleter gets per tick
	#Range: 1 ~ 1000
	"Deletion Time" = 10
	#Defines how many Dimensions can be generated at the same time, this is due to thread limitations mcs worldgen has. 0 => Single Dimension, 1 => Up to 3 dimensions (Ensures each dimension has at least 2 threads), 2 => Up to 5 Dimensions (Dimensions will fight over CPU Threads due to limitations)
	#Range: 0 ~ 2
	"Threading Rule" = 2
	#Defines if the pregenerator should automatically restart on server start. Automatically set to true when a task is running, and automatically set to false if no task is running
	auto-restart = false
	#Defines if each world should use multiple threads to generate. This feature can improve worldgen speed drastically, but deadlocks can happen with it too.
	#If deadlock issues happen, like the worldgen stops randomly, disabling this might fix it for you at the slight slowdown in worldgen
	#If the config is changed the pregeneration needs to be restarted
	"Multithreaded WorldGen" = true
	#Override increases the Watchdog Kill switch to a minimum of 10 minutes instead of 60 seconds. Because Heavy modpacks cause spikes that can last 60 seconds during pregen and saving, this just reduces crashes by minecraft itself and leaves the killswitch
	"Disable Watchdog Override" = false
	#Defines if the Improved Command Arguments should be used on Command Creation. If enabled mod is required on client
	"Advanced Command Arguments" = true
	#Defines how many Players have to be online for the Processor to Auto Pause, -1 = Disabled. It is Inclusive 2 = Allows 1 Player
	#Range: > -1
	"Player Limit" = -1

[client]

	[client.pregen-overlay]
		#Defines the Horizontal Alignment of the UI, left to right
		#Allowed Values: START, CENTER, END
		horizontal-alignment = "START"
		#Defines if the Pregen Overlay should be enabled
		pregen-overlay = true
		#Defines the Vertical Alignment of the UI, top to bottom
		#Allowed Values: START, CENTER, END
		vertical-alignment = "START"
		#Defines the Scale of the Overlay
		#Range: 0.1 ~ 10.0
		scale = 1.0

	[client.profiler-overlay]
		#Defines the Horizontal Alignment of the UI, left to right
		#Allowed Values: START, CENTER, END
		horizontal-alignment = "START"
		#Reference to save which dimension is currently detailed
		detailed-dimension = "minecraft:overworld"
		#Defines if the Profiler Overlay should be enabled
		profiler-overlay = true
		#Defines the Vertical Alignment of the UI, top to bottom
		#Allowed Values: START, CENTER, END
		vertical-alignment = "START"
		#Defines the Scale of the Overlay
		#Range: 0.1 ~ 10.0
		scale = 1.0

	[client.MiniMap]
		#This decides the LOD (Level Of Detail) of the MiniMap. This is here to ensure you can control how much GPU ram you will need
		#There are 4 modes, Auto, MAX, High, Medium
		#AUTO will basically ensure the minimap will never exceed 300MB of GPU ram per minimap
		#MAX will basically apply no LOD. Which at max radius (1k chunks) will require 4GB of GPU Ram
		#High is the first level of LOD. Which will only show 1/4th of the detail. Which will take at max radius 1GB of GPU ram
		#Medium is the second level of LOD. Which will only show 1/16th of the detail. Which will take at max radius 250MB of GPU Ram
		#Allowed Values: AUTO, MAX, HIGH, MEDIUM
		lod = "AUTO"
		#If you hover with your mouse over the MiniMap that it should show a large version of said miniMap
		large-hover = true
		#If you have access to this feature if it should be enabled. This will just turn off the MiniMap and disable any data synchronization
		enable-minimap = true
		#If you need to refresh the Supporter info set this to true and on the next game restart it will automatically update the info.
		update-supporters = false

