
#Everything to do with gameplay
[gameplay]
	#If true, anvils will show all metal variants. If false, only the first variant in the tag will show (typically tinkers bronze)
	showAllAnvilVariants = true
	#If true, tables such as the part builder and tinker station will show all variants. If false they will show just the first entry in the tag, typically oak.
	showAllTableVariants = false
	#Set this to false to disable new players spawning with the Tinkers' Book.
	shouldSpawnWithTinkersBook = false
	#If non-empty, only this material will be shown on tools in creative and JEI (or the first valid material if this is invalid for the tool).
	#If empty, all materials will show
	showOnlyToolMaterial = ""
	#If non-empty, only material will be shown on parts in creative and JEI (or the first valid material if this is invalid for the part).
	#If empty, all materials will show
	showOnlyPartMaterial = ""

#Options related to recipes, limited options as a datapack allows most recipes to be modified
[recipes]
	#Makes wither skeletons drop necrotic bones
	witherBoneDrop = true
	#Number of nuggets produced when an ore block is melted in the smeltery. 9 nuggets would give 1 ingot
	#Range: 1 ~ 45
	smelteryNuggetsPerOre = 18
	#Makes the recipe to alloy netherite in the smeltery only cost 2 gold per netherite ingot. If false uses the vanilla rate of 4 gold per ingot. Disable if there are crafting duplications.
	cheaperNetheriteAlloy = true
	#Add a recipe that allows you to craft a piece of flint using 3 gravel
	addGravelToFlintRecipe = true
	#Fixes clear glass not being usable in vanilla recipes that require glass. Config option exists to disable easily in case this fix is redundant to another mod
	glassRecipeFix = true
	#Number of nuggets produced when an ore block is melted in the foundry. 9 nuggets would give 1 ingot
	#Range: 1 ~ 45
	foundryNuggetsPerOre = 15
	#Allows converting wither bones to regular bones
	witherBoneConversion = true
	#Number of nuggets produced when an ore block is melted in the melter. 9 would give 1 ingot
	#Range: 1 ~ 45
	melterNuggetsPerOre = 12

	#Entity head drops when killed by a charged creeper
	[recipes.heads]
		stray = true
		husk = true
		blaze = true
		cave_spider = true
		drowned = true
		spider = true
		enderman = true

#Everything to do with world generation
[worldgen]
	#Generate Cobalt
	generateCobalt = true
	#Generate Copper
	generateCopper = false
	#Approx Ores per Chunk
	veinCountCobalt = 8
	#Approx Ores per Chunk
	veinCountCopper = 20

	#Options related to slime islands
	[worldgen.slime_islands]

		#Settings for sky slime islands in the overworld sky
		[worldgen.slime_islands.sky]
			#How many chunks on average between islands
			#Range: 10 ~ 500
			separation = 30
			#If true, this island generates
			generate = false

		#Options related to earth slime islands spawning in the oceans
		[worldgen.slime_islands.earth]
			#How many chunks on average between islands
			#Range: 10 ~ 500
			separation = 25
			#If true, this island generates
			generate = false

		#Settings for end slime islands in the outer end islands
		[worldgen.slime_islands.end]
			#How many chunks on average between islands
			#Range: 10 ~ 500
			separation = 25
			#If true, this island generates
			generate = true

		#Settings for blood islands in the nether lava ocean
		[worldgen.slime_islands.blood]
			#How many chunks on average between islands
			#Range: 10 ~ 500
			separation = 13
			#If true, this island generates
			generate = true

		#Settings for clay islands in the overworld sky
		[worldgen.slime_islands.clay]
			#How many chunks on average between islands
			#Range: 10 ~ 500
			separation = 100
			#If true, this island generates
			generate = false

#Features to use in debugging gameplay and mechanics, generally should not be enabled in packs
[debug]
	#If true, forces integration materials to be enabled, even if the relevant metal is missing. Useful for testing material balance.
	#Does not provide recipes for any of them, they will only be available to cheat in creative.
	forceIntegrationMaterials = false

