
[cosmetics]
	#The active cosmetic for the category: special
	active_cosmetic_special = ""
	#The active cosmetic for the category: back
	active_cosmetic_back = ""
	#The active cosmetic for the category: hat
	active_cosmetic_hat = ""
	#The active cosmetic for the category: face
	active_cosmetic_face = ""
	#The active cosmetic for the category: hand
	active_cosmetic_hand = ""

